inno-camp-final/Final-BE

src/main/java/com/havit/finalbe/controller/ParticipateController.java, src/main/java/com/havit/finalbe/entity/Participate.java, src/main/java/com/havit/finalbe/exception/ErrorMsg.java, src/main/java/com/havit/finalbe/repository/ParticipateRepository.java, src/main/java/com/havit/finalbe/service/ParticipateService.java
테스트할 수 있는 그룹 데이터가 아직 없어서 코드 테스트는 해보지 않았습니다.
그룹 데이터가 생성되면 바로 테스트 해보겠습니다.
아직 큰 에러 없이 실행 잘 됩니다.
=> [22-09-23] 그룹 참여하기 기능 구현

src/main/java/com/havit/finalbe/controller/CertifyController.java, src/main/java/com/havit/finalbe/dto/request/CertifyRequestDto.java, src/main/java/com/havit/finalbe/dto/request/LoginRequestDto.java, src/main/java/com/havit/finalbe/dto/request/SignupRequestDto.java, src/main/java/com/havit/finalbe/dto/response/CertifyResponseDto.java, src/main/java/com/havit/finalbe/dto/response/CommentResponseDto.java, src/main/java/com/havit/finalbe/dto/response/GroupResponseDto.java, src/main/java/com/havit/finalbe/dto/response/SubCommentResponseDto.java, src/main/java/com/havit/finalbe/entity/Certify.java, src/main/java/com/havit/finalbe/service/CertifyService.java
=> [22-09-24] 인증샷 수정

src/main/java/com/havit/finalbe/entity/Certify.java, src/main/java/com/havit/finalbe/entity/Comment.java, src/main/java/com/havit/finalbe/entity/Groups.java, src/main/java/com/havit/finalbe/entity/Member.java, src/main/java/com/havit/finalbe/entity/Participate.java, src/main/java/com/havit/finalbe/entity/SubComment.java, src/main/java/com/havit/finalbe/repository/ParticipateRepository.java, src/main/java/com/havit/finalbe/service/CertifyService.java, src/main/java/com/havit/finalbe/service/CommentService.java, src/main/java/com/havit/finalbe/service/GroupService.java, src/main/java/com/havit/finalbe/service/ParticipateService.java, src/main/java/com/havit/finalbe/service/ServiceUtil.java, src/main/java/com/havit/finalbe/service/SubCommentService.java
=> [22-09-24] 코드 수정

src/main/java/com/havit/finalbe/controller/GroupController.java, src/main/java/com/havit/finalbe/dto/response/AllGroupListResponseDto.java, src/main/java/com/havit/finalbe/exception/ErrorMsg.java, src/main/java/com/havit/finalbe/repository/GroupRepository.java, src/main/java/com/havit/finalbe/repository/GroupTagRepository.java, src/main/java/com/havit/finalbe/service/CertifyService.java, src/main/java/com/havit/finalbe/service/GroupService.java
GroupService, CertifyService 에서 이미지 입력을 받지 않으면 null 로 저장이 되어 삭제가 불가능한 부분도 함께 수정했습니다!
=> [22-09-25] 태그별 그룹 전체 목록 조회

src/main/java/com/havit/finalbe/entity/Member.java
Response에 회원 암호화 된 비밀번호가 같이 나와서 추가했습니다.
=> [22-09-25] 멤버 비밀번호 @JsonIgnore 추가

src/main/java/com/havit/finalbe/controller/FavoriteController.java, src/main/java/com/havit/finalbe/dto/request/FavoriteRequestDto.java, src/main/java/com/havit/finalbe/entity/Favorite.java, src/main/java/com/havit/finalbe/entity/Groups.java, src/main/java/com/havit/finalbe/repository/FavoriteRepository.java, src/main/java/com/havit/finalbe/service/FavoriteService.java, src/main/java/com/havit/finalbe/service/GroupService.java, src/main/java/com/havit/finalbe/service/ParticipateService.java
=> [22-09-26] 즐겨찾기 기능 구현

src/main/java/com/havit/finalbe/configuration/SwaggerConfig.java
=> [22-09-26] Swagger 값 추가

src/main/java/com/havit/finalbe/controller/CertifyController.java, src/main/java/com/havit/finalbe/controller/GroupController.java, src/main/java/com/havit/finalbe/controller/MainController.java, src/main/java/com/havit/finalbe/dto/CertifyDto.java
=> [22-09-26] Swagger 오류 해결

src/main/java/com/havit/finalbe/dto/CertifyDto.java, src/main/java/com/havit/finalbe/jwt/util/TokenProperties.java, src/main/java/com/havit/finalbe/service/MemberService.java
[22-09-27] tokenProperties + certifyDto change
=> [22-09-27] tokenProperties + certifyDto change

src/main/java/com/havit/finalbe/controller/MyPageController.java, src/main/java/com/havit/finalbe/dto/MemberDto.java, src/main/java/com/havit/finalbe/entity/Groups.java, src/main/java/com/havit/finalbe/entity/Member.java, src/main/java/com/havit/finalbe/exception/ErrorMsg.java, src/main/java/com/havit/finalbe/repository/MemberRepository.java, src/main/java/com/havit/finalbe/service/CertifyService.java, src/main/java/com/havit/finalbe/service/CommentService.java, src/main/java/com/havit/finalbe/service/FavoriteService.java, src/main/java/com/havit/finalbe/service/MemberService.java, src/main/java/com/havit/finalbe/service/MyPageService.java, src/main/java/com/havit/finalbe/service/ParticipateService.java, src/main/java/com/havit/finalbe/service/SubCommentService.java
[22-09-28] 비밀번호 확인, 내 정보 수정, 프로필 사진 삭제 기능 구현
=> [22-09-28] 비밀번호 확인, 내 정보 수정, 프로필 사진 삭제 기능 구현

src/main/java/com/havit/finalbe/controller/MemberController.java, src/main/java/com/havit/finalbe/jwt/util/JwtUtil.java, src/main/java/com/havit/finalbe/jwt/util/TokenProperties.java, src/main/java/com/havit/finalbe/service/MemberService.java
=> [22-09-28] token 관련 업데이트

src/main/java/com/havit/finalbe/configuration/SwaggerConfig.java, src/main/java/com/havit/finalbe/controller/CertifyController.java, src/main/java/com/havit/finalbe/controller/CommentController.java, src/main/java/com/havit/finalbe/controller/FavoriteController.java, src/main/java/com/havit/finalbe/controller/GroupController.java, src/main/java/com/havit/finalbe/controller/MainController.java, src/main/java/com/havit/finalbe/controller/MyPageController.java, src/main/java/com/havit/finalbe/controller/ParticipateController.java, src/main/java/com/havit/finalbe/controller/SubCommentController.java, src/main/java/com/havit/finalbe/dto/CertifyDto.java, src/main/java/com/havit/finalbe/entity/Certify.java, src/main/java/com/havit/finalbe/entity/Groups.java, src/main/java/com/havit/finalbe/entity/Member.java, src/main/java/com/havit/finalbe/entity/SubComment.java, src/main/java/com/havit/finalbe/service/CertifyService.java, src/main/java/com/havit/finalbe/service/CommentService.java, src/main/java/com/havit/finalbe/service/FavoriteService.java, src/main/java/com/havit/finalbe/service/GroupService.java, src/main/java/com/havit/finalbe/service/MainService.java, src/main/java/com/havit/finalbe/service/MyPageService.java, src/main/java/com/havit/finalbe/service/ParticipateService.java, src/main/java/com/havit/finalbe/service/ServiceUtil.java, src/main/java/com/havit/finalbe/service/SubCommentService.java
[22-09-28] 회원 인증 부분 전체 수정, PATCH 예외처리 추가
=> [22-09-28] 회원 인증 부분 전체 수정, PATCH 예외처리 추가

src/main/java/com/havit/finalbe/service/CertifyService.java, src/main/java/com/havit/finalbe/service/GroupService.java
=> [22-09-28] 이미지 코드 수정

src/main/java/com/havit/finalbe/controller/MemberController.java, src/main/java/com/havit/finalbe/jwt/util/JwtUtil.java, src/main/java/com/havit/finalbe/service/MemberService.java
[22-09-28] 토큰 payload username에서 memberId로 변경
=> [22-09-28] 토큰 payload username에서 memberId로 변경

src/main/java/com/havit/finalbe/jwt/util/JwtUtil.java, src/main/java/com/havit/finalbe/service/MemberService.java
[22-09-28] token payload memberId 추가
=> [22-09-28] token payload memberId 추가

src/main/java/com/havit/finalbe/configuration/SwaggerConfig.java
[22-09-28] Swagger 인증 Refresh-Token 추가
=> [22-09-28] Swagger 인증 Refresh-Token 추가

src/main/java/com/havit/finalbe/controller/GroupController.java
[22-09-28] Group Controller 수정
=> [22-09-28] Group Controller 수정

src/main/java/com/havit/finalbe/controller/CertifyController.java, src/main/java/com/havit/finalbe/controller/CommentController.java, src/main/java/com/havit/finalbe/controller/FavoriteController.java, src/main/java/com/havit/finalbe/controller/GroupController.java, src/main/java/com/havit/finalbe/controller/MainController.java, src/main/java/com/havit/finalbe/controller/MemberController.java, src/main/java/com/havit/finalbe/controller/MyPageController.java, src/main/java/com/havit/finalbe/controller/ParticipateController.java, src/main/java/com/havit/finalbe/controller/SubCommentController.java
=> [22-09-28] swagger 설정 변경

src/main/java/com/havit/finalbe/service/MyPageService.java
[22-09-28] 비밀번호 확인 반환값 bool로 변경
=> [22-09-28] 비밀번호 확인 반환값 bool로 변경

src/main/java/com/havit/finalbe/dto/MemberDto.java, src/main/java/com/havit/finalbe/entity/Member.java, src/main/java/com/havit/finalbe/service/MemberService.java, src/main/java/com/havit/finalbe/service/MyPageService.java
내 정보 수정할 때 한 줄 소개도 같이 수정할 수 있는 부분을 추가했습니다.
memberResponse에 introduce 추가되어 응답합니다.
```
{
"data": {
"memberId": 9,
"username": "jini@naver.com",
"nickname": "지니뺭",
"profileUrl": null,
"introduce": "지니는 짱짱맨이다!!!",
"createdAt": "2022-09-28T23:15:21.246171",
"modifiedAt": "2022-09-29T03:28:54.571057"
},
"errorMsg": null
}
```
=> [22-09-29] 내 정보 수정 소개란 추가

src/main/java/com/havit/finalbe/configuration/SwaggerConfig.java
[22-09-29] swagger @AuthenticationPrincipal 무시
=> [22-09-29] swagger @AuthenticationPrincipal 무시

src/main/java/com/havit/finalbe/controller/MemberController.java, src/main/java/com/havit/finalbe/service/MemberService.java
=> [22-09-29] 멤버 객체 반환 api

src/main/java/com/havit/finalbe/controller/MemberController.java
=> [22-09-29] 멤버 정보 반환 API

src/main/java/com/havit/finalbe/controller/CertifyController.java, src/main/java/com/havit/finalbe/controller/CommentController.java, src/main/java/com/havit/finalbe/controller/FavoriteController.java, src/main/java/com/havit/finalbe/controller/GroupController.java, src/main/java/com/havit/finalbe/controller/MainController.java, src/main/java/com/havit/finalbe/controller/MemberController.java, src/main/java/com/havit/finalbe/controller/MyPageController.java, src/main/java/com/havit/finalbe/controller/ParticipateController.java, src/main/java/com/havit/finalbe/controller/SubCommentController.java, src/main/java/com/havit/finalbe/service/CertifyService.java, src/main/java/com/havit/finalbe/service/CommentService.java, src/main/java/com/havit/finalbe/service/FavoriteService.java, src/main/java/com/havit/finalbe/service/GroupService.java, src/main/java/com/havit/finalbe/service/MainService.java, src/main/java/com/havit/finalbe/service/MemberService.java, src/main/java/com/havit/finalbe/service/MyPageService.java, src/main/java/com/havit/finalbe/service/ParticipateService.java, src/main/java/com/havit/finalbe/service/SubCommentService.java
=> [22-09-29] ResponseDto<?> 타입 수정

src/main/java/com/havit/finalbe/controller/MyPageController.java, src/main/java/com/havit/finalbe/repository/GroupRepository.java, src/main/java/com/havit/finalbe/repository/ParticipateRepository.java, src/main/java/com/havit/finalbe/service/GroupService.java, src/main/java/com/havit/finalbe/service/MainService.java, src/main/java/com/havit/finalbe/service/MyPageService.java
내가 참여한 그룹과 내가 만든 그룹을 함께 조회할 수 있습니다.
아래의 응답에서 1번 그룹은 내가 만들진 않았지만 내가 참여한 그룹이고, 3번 그룹은 내가 만들었지만 참여하지 않은 그룹입니다.
```
{
"data": [
{
"groupId": 3,
"title": "하루 1만보 걷기",
"imgUrl": "https://havitbucket.s3.ap-northeast-2.amazonaws.com/group/7e06c0bd-12d6-45dd-9d89-e6e1de374d02imgFile",
"memberCount": 0,
"groupTag": [
"걷기",
"운동",
"루틴",
"건강"
],
"favorite": true,
"createdAt": "2022-09-29T16:10:52.240173",
"modifiedAt": "2022-09-29T16:12:31.057303"
},
{
"groupId": 1,
"title": "매일 출근하는 사람들",
"imgUrl": "https://havitbucket.s3.ap-northeast-2.amazonaws.com/group/c5d13804-ffc9-4602-a43d-e6d0bbcefbbeimgFile",
"memberCount": 2,
"groupTag": [
"신입사원",
"미생",
"회사",
"출근"
],
"favorite": true,
"createdAt": "2022-09-29T04:43:50.190987",
"modifiedAt": "2022-09-29T04:43:50.190987"
}
],
"errorMsg": null
}
```
여기서 1번 그룹은 …
=> [22-09-29] 즐겨찾기 수정, 마이 페이지 기능 추가

src/main/java/com/havit/finalbe/entity/Certify.java
=> [22-09-29] imgUrl nullable 수정

src/main/java/com/havit/finalbe/jwt/util/JwtUtil.java
=> [22-09-29] 데이터 반환 타입 변경

src/main/java/com/havit/finalbe/service/ImageService.java
=> [22-09-30] 수정 부분 오류 해결

src/main/java/com/havit/finalbe/service/ImageService.java
=> [ 22-09-30] 이미지 관련 코드 수정

src/main/java/com/havit/finalbe/controller/ImageController.java, src/main/java/com/havit/finalbe/service/ImageService.java
=> [22-09-30] 이미지 업로드 관련 코드 수정

src/main/java/com/havit/finalbe/entity/Image.java, src/main/java/com/havit/finalbe/service/ImageService.java
[22-10-01] Image entity img_Url delete
=> [22-10-01] Image entity img_Url delete

src/main/java/com/havit/finalbe/controller/CertifyController.java, src/main/java/com/havit/finalbe/controller/GroupController.java, src/main/java/com/havit/finalbe/controller/ImageController.java, src/main/java/com/havit/finalbe/controller/MyPageController.java, src/main/java/com/havit/finalbe/dto/GroupDto.java, src/main/java/com/havit/finalbe/dto/MemberDto.java, src/main/java/com/havit/finalbe/entity/Groups.java, src/main/java/com/havit/finalbe/entity/Member.java, src/main/java/com/havit/finalbe/service/CertifyService.java, src/main/java/com/havit/finalbe/service/GroupService.java, src/main/java/com/havit/finalbe/service/ImageService.java, src/main/java/com/havit/finalbe/service/MyPageService.java, src/main/java/com/havit/finalbe/service/ParticipateService.java
=> [22-10-01] 코드 전체 수정

src/main/java/com/havit/finalbe/dto/response/MessageResponseDto.java, src/main/java/com/havit/finalbe/exception/CustomException.java, src/main/java/com/havit/finalbe/exception/CustomExceptionHandler.java, src/main/java/com/havit/finalbe/exception/ErrorCode.java, src/main/java/com/havit/finalbe/exception/ErrorResponseEntity.java, src/main/java/com/havit/finalbe/service/CertifyService.java, src/main/java/com/havit/finalbe/service/CommentService.java, src/main/java/com/havit/finalbe/service/FavoriteService.java, src/main/java/com/havit/finalbe/service/GroupService.java, src/main/java/com/havit/finalbe/service/ImageService.java, src/main/java/com/havit/finalbe/service/MemberService.java, src/main/java/com/havit/finalbe/service/MyPageService.java, src/main/java/com/havit/finalbe/service/ParticipateService.java, src/main/java/com/havit/finalbe/service/SubCommentService.java
[22-10-01] ExceptionHandler used to send error message via response
=> [22-10-01] ExceptionHandler used to send error message via response

src/main/java/com/havit/finalbe/controller/CertifyController.java, src/main/java/com/havit/finalbe/controller/GroupController.java, src/main/java/com/havit/finalbe/service/CertifyService.java, src/main/java/com/havit/finalbe/service/GroupService.java, src/main/java/com/havit/finalbe/service/ImageService.java
=> [22-10-01] 코드 정리

src/main/java/com/havit/finalbe/service/MemberService.java
[22-10-01] exception handled on signup
=> [22-10-01] exception handled on signup

src/main/java/com/havit/finalbe/repository/CertifyRepository.java, src/main/java/com/havit/finalbe/service/GroupService.java, src/main/java/com/havit/finalbe/service/ParticipateService.java
```
{
"groupId": 13,
"title": "디자인 합시다;;^^;;",
"writer": {
"createdAt": "2022-10-03T11:02:26.286158",
"modifiedAt": "2022-10-04T16:38:58.054438",
"memberId": 5,
"username": "zzzz@naver.com",
"nickname": "❤동방삭",
"imageId": 31,
"introduce": "삼천갑자동방삭",
"hibernateLazyInitializer": {}
},
"leaderName": "구스타프클림트",
"crewName": "에곤쉴레",
"startDate": "2022-10-05",
"content": "매일 저랑 로고 디자인하실분?\n포폴 ㄱㄱ 합시다",
"imageId": 32,
"createdAt": "2022-10-04T16:54:04.772112",
"modifiedAt": "2022-10-04T16:54:04.772112",
"groupTag": [
"디자이너",
"디자이노"
],
"memberCount": 3,
"memberList": [
{
"createdAt": "2022-10-03T11:02:26.286158",
"modifiedAt": "2022-10-04T16:38:58.054438",
"memberId": 5,
"username": "zzzz@naver.com",
"nickname": "❤동방삭",
"imageId": 31,
"introduce": "삼천갑자동방삭",
"hibernateLazyInitializer": {}
},
{ …
```
=> [22-10-05] 인증샷 최신순 정렬 수정

src/main/java/com/havit/finalbe/dto/request/CertifyRequestDto.java, src/main/java/com/havit/finalbe/dto/request/GroupRequestDto.java, src/main/java/com/havit/finalbe/exception/ValidException.java
- NotNull
- NotEmpty
- NotBlank
에러명과 어느 부분에서 빈 칸이 확인되었는지 desc도 함께 출력
```
{
"errorcode": "NotBlank",
"message": "제목은 빈 칸일 수 없습니다."
}
```
=> [22-10-07] @Valid 400 Error Message 추가

src/main/java/com/havit/finalbe/service/MyPageService.java
특정 이미지가 자꾸 db, s3에서 삭제되는 상황이 발생해서 이미지 삭제 관련 코드들의 조건문을 수정했습니다.
=> [22-10-12] 프로필 사진 삭제 조건 수정

src/main/java/com/havit/finalbe/controller/NotificationController.java, src/main/java/com/havit/finalbe/dto/request/NotificationRequestDto.java, src/main/java/com/havit/finalbe/dto/response/NotificationResponseDto.java, src/main/java/com/havit/finalbe/dto/response/NotificationsResponseDto.java, src/main/java/com/havit/finalbe/entity/Notification.java, src/main/java/com/havit/finalbe/exception/ErrorCode.java, src/main/java/com/havit/finalbe/repository/EmitterRepository.java, src/main/java/com/havit/finalbe/repository/NotificationRepository.java, src/main/java/com/havit/finalbe/service/NotificationService.java
- SSE 연결
- 알림 보내기
- 내게 온 알림 목록 조회 (읽지 않은 알림 카운트 포함)
- 알림 읽음 처리하기
true : 읽음 / false : 안 읽음
=> [22-10-13] 알림 기능 구현

src/main/java/com/havit/finalbe/service/MyPageService.java
성준님 계정 내 정보 수정 안되는 이유가 이미지 null 체크에서 꼬인 것 같아요. 수정하니까 정상적으로 됩니다!
=> [22-10-16] 내 정보 수정 버그 해결
